services:
  proxy:
    build: ./proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/Caddyfile.dev:/etc/caddy/Caddyfile:ro,z

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web/src:/app/src:z
      - ./web/public:/app/public:z
      - ./web/index.html:/app/index.html:z
      - ./web/vite.config.ts:/app/vite.config.ts:z
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081
    networks:
      - frontend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app:z
    environment:
      - DB_SSLMODE=disable
      - INSTANCE_HOSTNAME=localhost
    ports:
      - "8081:8080"

  db:
    ports:
      - "5432:5432"
