FROM alpine:3.20

RUN apk add --no-cache \
    postgresql16-client \
    openssl \
    coreutils \
    && addgroup -g 1000 -S healthvault \
    && adduser -u 1000 -S healthvault -G healthvault

COPY verify.sh /usr/local/bin/verify.sh
RUN chmod +x /usr/local/bin/verify.sh

USER healthvault:healthvault

ENTRYPOINT ["sh", "-c"]
CMD ["while true; do /usr/local/bin/verify.sh; sleep ${VERIFY_INTERVAL:-604800}; done"]
