ALTER TABLE medical_contacts
  DROP COLUMN IF EXISTS contact_type,
  DROP COLUMN IF EXISTS street,
  DROP COLUMN IF EXISTS postal_code,
  DROP COLUMN IF EXISTS city,
  DROP COLUMN IF EXISTS country,
  DROP COLUMN IF EXISTS latitude,
  DROP COLUMN IF EXISTS longitude;
