root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/healthvault"
  cmd = "go build -o ./tmp/healthvault ./cmd/healthvault"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "sql"]
  kill_delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
